server:
  port: 7001
  servlet:
    context-path: /project-repository-admin

spring:
  application:
    name: project-repository-admin
  security:
    user:
      name: root
      password: root
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${nacosEndpoint}
        namespace: ${projectNamespace}
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user.name: root
          user.password: root
  thymeleaf:
    check-template: false
    check-template-location: false

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always
