### 登录
POST 127.0.0.1:9001/repository/project-repository/login
Content-Type: application/json

{
  "username": "faker",
  "password": "25d55ad283aa400af464c76d713c07ad"
}

### 注册
POST 127.0.0.1:9001/repository/project-repository/register
Content-Type: application/json

{
  "username": "faker3",
  "password": "25d55ad283aa400af464c76d713c07ad"
}
