### 查询服务
GET http://127.0.0.1:9001/repository/project-repository-nacos-client/nacos-client/service_instance?service_id=project-repository-gateway
Accept: application/json
repository-user: eyJhbGciOiJSUzI1NiJ9.eyJyZXBvc2l0b3J5LXVzZXIiOiJ7XCJpZFwiOjMwLFwibmFtZVwiOlwiZmFrZXJcIn0iLCJqdGkiOiI2NGZlMGY3YS01NGE4LTQyMWItYjg1ZC01M2I3YTQ0OTEwNTUiLCJleHAiOjE3MTI4NTEyMDB9.ND93-DuS3pkD5cbrVMfXfUMpOm0r8ioYsUpfBPg5xc3H7CGwOfZRd7CaI7DuX7UqJ0LwSVx208DgCLjXqiG-XdaLbgrFAsejV2U-XzIXNnXOwhIgLCQiCgwungeGjoiWUadCtX_lKrCPQdaWcIynMOSWYJunUdTZL8pHZRkoUFHBuvkVIhY1Yl7zC6JWXo7itz9Mb4JSe7Z1qY6hnILcgFz_WwYUzlOJEmOk5JAgKntR-VntO21c0gKAul1T6FfyA_nL_Xb-ysNxf0-Zbz0OIPtnlzRt2g0txKIBjNFnBV6aSpG6qMNTNiET4jvnrFFwVYjCp3SbIXoXijKhzsqsQA
token: repository
