### 查询服务
GET http://127.0.0.1:9001/repository/project-repository-nacos-client/nacos-client/service_instance?service_id=project-repository-gateway
Accept: application/json
repository-user: eyJhbGciOiJSUzI1NiJ9.eyJyZXBvc2l0b3J5LXVzZXIiOiJ7XCJpZFwiOjMyLFwibmFtZVwiOlwiZmFrZXIzXCJ9IiwianRpIjoiNzhkMjJkMmQtOWUyNC00MTE5LWFkNGMtZmVhODI5ZTU0NDdlIiwiZXhwIjoxNzEyNzY0ODAwfQ.BqMJOeeMcnBfvLLfNOdSgppE4Vhi-E64GbTYvIyRtM6GDYKKprCd5SRB20zGz6d6cCpEV8F97CcLIlhVZr3gu9t6wadCBKA6SyiCspdxnt1BL1_vSi6Yi0Hb8Hv-ah_Ezi0M6lr9p3eisUFWYPCfO798yi_hDOvfuCEYygWqSt3KF6Xld9UH59_F_DHXn4CryH4D8fqcdjug1ycSc34SAvSj_I0DcUeXYUDg3vCyF7TXtT5xie1I69mi2xUEM68m9KFHrSBbAnrqWhg3hQWhAh8yqvglqEr33oDe1-4nbjejdaa3NP8TfHICiWiZdocliCV2vGFCaNLEw22b2sAEag
token: repository
