### 发送默认信道消息
GET http://127.0.0.1:8006/project-stream-client/stream-message/default-send
Content-Type: application/json

### 发送自定义信道消息
GET http://127.0.0.1:8006/project-stream-client/stream-message/custom-send
Content-Type: application/json
