### 导入商品
POST http://127.0.0.1:9001/repository/project-repository-goods-service/async-goods/import-goods
Content-Type: application/json
repository-user: eyJhbGciOiJSUzI1NiJ9.eyJyZXBvc2l0b3J5LXVzZXIiOiJ7XCJpZFwiOjMwLFwibmFtZVwiOlwiZmFrZXJcIn0iLCJqdGkiOiIzYWJhMzA3MS1hODhkLTRjYzUtODg3My1mYjg3YmViZGFiYzQiLCJleHAiOjE3MTI5Mzc2MDB9.iaKI0lvdbfls0PlkfwA2UdxZSzo7CQRdeIQbHvo3hZ0cOm8Z1qmIRF2Adpr3VfPJ0TnkrH-ZRGjPNmUeSFDlA-swAMWeJJeG-cRPiuwY7sxZhVP_I9b-ruXYhGwCPW4_xMDQ0nG1jXwnnxwtSfixykg1-V3b2E1lD2Ri6pgpzjKUkO5KirEJgVfx0XtnR5BOTQncrKoWJLUiFstoRUHxiOE_gbc3fdmCHJD8e5X8iT-3rfSnT2A8gPAIS8eOIx0lHBudiggWAJ8Kp6WQYfYRg89RjXWlaMHkNoHWQapYRSTSMlu0ZwuxclfRj8vSfnQi_8JAP-LzfFWzPapIGRPbdw

[
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 11",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 100000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 12",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 150000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  },
  {
    "goodsCategory": "10001",
    "brandCategory": "20001",
    "goodsName": "iphone 13",
    "goodsPic": "",
    "goodsDescription": "苹果手机",
    "price": 160000,
    "supply": 2000000,
    "goodsProperty": {
      "size": "12cm * 6.5cm",
      "color": "绿色",
      "material": "金属机身",
      "pattern": "纯色"
    }
  }
]


### 查询导入商品状态
GET http://127.0.0.1:9001/repository/project-repository-goods-service/async-goods/task-info?taskId=f2ef2676-883f-4d33-ae8a-770dd8add665
Accept: application/json
repository-user: eyJhbGciOiJSUzI1NiJ9.eyJyZXBvc2l0b3J5LXVzZXIiOiJ7XCJpZFwiOjMwLFwibmFtZVwiOlwiZmFrZXJcIn0iLCJqdGkiOiIzYWJhMzA3MS1hODhkLTRjYzUtODg3My1mYjg3YmViZGFiYzQiLCJleHAiOjE3MTI5Mzc2MDB9.iaKI0lvdbfls0PlkfwA2UdxZSzo7CQRdeIQbHvo3hZ0cOm8Z1qmIRF2Adpr3VfPJ0TnkrH-ZRGjPNmUeSFDlA-swAMWeJJeG-cRPiuwY7sxZhVP_I9b-ruXYhGwCPW4_xMDQ0nG1jXwnnxwtSfixykg1-V3b2E1lD2Ri6pgpzjKUkO5KirEJgVfx0XtnR5BOTQncrKoWJLUiFstoRUHxiOE_gbc3fdmCHJD8e5X8iT-3rfSnT2A8gPAIS8eOIx0lHBudiggWAJ8Kp6WQYfYRg89RjXWlaMHkNoHWQapYRSTSMlu0ZwuxclfRj8vSfnQi_8JAP-LzfFWzPapIGRPbdw
