server:
  port: 8001
  servlet:
    context-path: /kafka-study

spring:
  kafka:
    # springboot 集成kafka的配置, 最低配置只需要配置spring.kafka.bootstrap-servers
    bootstrap-servers: 127.0.0.1:9092

# rocketmq配置 最低配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group, 保证group唯一
    group: project-rocketmq